Allow audio to play while fast forwarding
Swordfish90/LibretroDroid pull request #29
Opened 2020-10-16 17:48 UTC by tytydraco

I think it's better to play the audio even if it is distorted. It lets
users gauge how fast the game is playing.

2020-10-16 22:06 UTC, Swordfish90 commented
I'm not against this feature as the choice might be up to the application using LibretroDroid.

What this pull request is missing though is telling the audio engine that it should play audio at double the sample rate to reduce audio glitching.

2020-10-16 22:07 UTC, Swordfish90 requested changes
I'm not against this feature as the choice might be up to the application using LibretroDroid.

What this pull request is missing though is telling the audio engine that it should play audio at double the sample rate to reduce audio glitching.

2020-10-16 23:32 UTC, tytydraco commented
Is this as easy as just checking if fast forward is enabled and doubling the `frames` parameter here? It looks like that would double the final sample rate:

```
size_t frameMultiplier = fastForwardEnabled ? 2 : 1
audio->write(data, frames * frameMultiplier );
```

Does that look right to you?

2020-10-17 00:28 UTC, Swordfish90 commented
A bit more tricky. That's where we write data into the Lemuroid audio buffer (with the emulator sample rate). You need to do something like that in the oboe callback, where we read defaultSampleRate. The defaultSampleRate value should be doubled when fast forward is enabled.

2020-10-17 00:39 UTC, tytydraco commented
Gotcha. I'll be working on it :)

2020-10-17 04:44 UTC, tytydraco commented
Boom! Pushed my changes. I tested locally on my own project, works beautifully. Let me know if you have any improvements to my implementation. I would be more than happy to accommodate suggestions. I am super passionate about this project so I'm willing to settle for nothing less than perfect. 🤟

2020-10-17 09:49 UTC, Swordfish90 commented
That's awesome! It looks great and the buffer doesn't overrun nor underrun with the current buffer size, I'm going to merge it.

Thank you very much for opening a pull request on this one!

2020-10-17 09:49 UTC, merged